# Form implementation generated from reading ui file 'app_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 580)
        Dialog.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.frame_1 = QtWidgets.QFrame(parent=Dialog)
        self.frame_1.setGeometry(QtCore.QRect(30, 20, 661, 81))
        self.frame_1.setStyleSheet("border-radius: 15;\n"
"background-color:  rgb(229, 229, 229);\n"
"color:rgb(0, 0, 0)")
        self.frame_1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_1.setObjectName("frame_1")
        self.label_title = QtWidgets.QLabel(parent=self.frame_1)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(False)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.app_title = QtWidgets.QLabel(parent=self.frame_1)
        self.app_title.setGeometry(QtCore.QRect(10, 30, 631, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.app_title.setFont(font)
        self.app_title.setText("")
        self.app_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.app_title.setObjectName("app_title")
        self.frame_2 = QtWidgets.QFrame(parent=Dialog)
        self.frame_2.setGeometry(QtCore.QRect(30, 110, 661, 441))
        self.frame_2.setStyleSheet("border-radius: 15;\n"
"background-color:  rgb(229, 229, 229);\n"
"color:rgb(0, 0, 0)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.label_text = QtWidgets.QLabel(parent=self.frame_2)
        self.label_text.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(False)
        self.label_text.setFont(font)
        self.label_text.setObjectName("label_text")
        self.app_text = QtWidgets.QLabel(parent=self.frame_2)
        self.app_text.setGeometry(QtCore.QRect(10, 30, 631, 351))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.app_text.setFont(font)
        self.app_text.setText("")
        self.app_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.app_text.setWordWrap(True)
        self.app_text.setObjectName("app_text")
        self.app_date = QtWidgets.QLabel(parent=self.frame_2)
        self.app_date.setGeometry(QtCore.QRect(540, 410, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.app_date.setFont(font)
        self.app_date.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.app_date.setObjectName("app_date")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_title.setText(_translate("Dialog", "Заголовок"))
        self.label_text.setText(_translate("Dialog", "Содержание"))
        self.app_date.setText(_translate("Dialog", "TextLabel"))
