# Form implementation generated from reading ui file 'applicationWin.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog


class Ui_Dialog(QDialog):
    # def __init__(self):
    #     super().__init__()
    #     self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(686, 487)
        Dialog.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.title_input = QtWidgets.QLineEdit(parent=Dialog)
        self.title_input.setGeometry(QtCore.QRect(30, 40, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.title_input.setFont(font)
        self.title_input.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(243, 243, 243)")
        self.title_input.setReadOnly(False)
        self.title_input.setObjectName("title_input")
        self.button_send = QtWidgets.QPushButton(parent=Dialog)
        self.button_send.setGeometry(QtCore.QRect(40, 410, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        font.setBold(True)
        self.button_send.setFont(font)
        self.button_send.setStyleSheet("border-radius: 15;\n"
"color:rgb(0, 0, 0);\n"
"background-color:  rgb(229, 229, 229)")
        self.button_send.setObjectName("button_send")
        self.text_input = QtWidgets.QTextEdit(parent=Dialog)
        self.text_input.setGeometry(QtCore.QRect(30, 100, 621, 301))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.text_input.setFont(font)
        self.text_input.setStyleSheet("border-radius:15;\n"
"color:rgb(0, 0, 0);\n"
"background-color:rgb(243, 243, 243)")
        self.text_input.setObjectName("text_input")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_input.setPlaceholderText(_translate("Dialog", "Введите заголовок"))
        self.button_send.setText(_translate("Dialog", "Отправить"))
        self.text_input.setPlaceholderText(_translate("Dialog", "Введите текст"))
