# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog, QLineEdit


class Ui_MainWindow(QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("MainWindow")
        Dialog.resize(747, 552)
        Dialog.setStyleSheet("background-color: #ffffff")
        # Dialog.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=Dialog)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 110, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(21)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 0, 0)")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(210, 180, 311, 241))
        self.frame_4.setStyleSheet("border-radius: 15;\n"
"background-color:  rgb(245, 245, 245)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setObjectName("frame_4")

        self.login_widget = QtWidgets.QLineEdit(parent=self.frame_4)
        self.login_widget.setGeometry(QtCore.QRect(20, 40, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.login_widget.setFont(font)
        self.login_widget.setStyleSheet("color: rgb(0, 0, 0);\n"
"radius: 5;\n"
"background-color:  rgb(225, 225, 225)")
        self.login_widget.setObjectName("login_widget")
        self.login_widget.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.label_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 49, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(0,0,0)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(0,0,0)")
        self.label_3.setObjectName("label_3")
        self.password_widget = QtWidgets.QLineEdit(parent=self.frame_4)
        self.password_widget.setGeometry(QtCore.QRect(20, 110, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.password_widget.setFont(font)
        self.password_widget.setStyleSheet("color: rgb(0, 0, 0);\n"
"radius: 5;\n"
"background-color:  rgb(225, 225, 225)")
        self.password_widget.setText("")
        self.password_widget.setObjectName("password_widget")
        self.password_widget.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password_widget.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)

        self.logIn_btn = QtWidgets.QPushButton(parent=self.frame_4)
        self.logIn_btn.setGeometry(QtCore.QRect(90, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        font.setBold(False)
        self.logIn_btn.setFont(font)
        self.logIn_btn.setStyleSheet("border-radius: 10;\n"
"background-color:  rgb(229, 229, 229);\n"
"color:rgb(0, 0, 0)")
        self.logIn_btn.setObjectName("logIn_btn")


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Добро пожаловать"))
        self.login_widget.setPlaceholderText(_translate("MainWindow", "Введите логин"))
        self.label_2.setText(_translate("MainWindow", "Логин"))
        self.label_3.setText(_translate("MainWindow", "Пароль"))
        self.password_widget.setPlaceholderText(_translate("MainWindow", "Введите пароль"))
        self.logIn_btn.setText(_translate("MainWindow", "Войти"))
