
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QDialog

# from MainWindowCode import ClickLabel


class MainWindow(QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(704, 587)
        Dialog.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 90, 701, 491))
        self.tabWidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(240, 240, 240);")
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")

        self.Info = QtWidgets.QWidget()
        self.Info.setAutoFillBackground(False)
        self.Info.setStyleSheet("")
        self.Info.setObjectName("Info")

        self.frame = QtWidgets.QFrame(parent=self.Info)
        self.frame.setGeometry(QtCore.QRect(10, 10, 371, 81))
        self.frame.setStyleSheet("border-radius: 15;\n"
"background-color:  rgb(229, 229, 229)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")

        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.user_name = QtWidgets.QLabel(parent=self.frame)
        self.user_name.setGeometry(QtCore.QRect(10, 30, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(15)
        self.user_name.setFont(font)
        self.user_name.setObjectName("user_name")

        self.frame_2 = QtWidgets.QFrame(parent=self.Info)
        self.frame_2.setGeometry(QtCore.QRect(400, 10, 281, 411))
        self.frame_2.setStyleSheet("border-radius: 15;\n"
"background-color:  rgb(229, 229, 229)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setObjectName("frame_2")

        self.label_5 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(15)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.user_room = QtWidgets.QLabel(parent=self.frame_2)
        self.user_room.setGeometry(QtCore.QRect(10, 40, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.user_room.setFont(font)
        self.user_room.setObjectName("user_room")

        self.label_15 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(10, 80, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")

        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.frame_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 120, 251, 251))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")

        self.scroll_widget_2 = QtWidgets.QWidget()
        self.scroll_layout_2 = QtWidgets.QVBoxLayout(self.scroll_widget_2)
        self.scroll_layout_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea_2.setWidget(self.scroll_widget_2)

        self.frame_3 = QtWidgets.QFrame(parent=self.Info)
        self.frame_3.setGeometry(QtCore.QRect(10, 110, 371, 311))
        self.frame_3.setStyleSheet("border-radius: 15;\n"
"background-color:  rgb(229, 229, 229)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setObjectName("frame_3")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(10, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")

        self.user_mail = QtWidgets.QLabel(parent=self.frame_3)
        self.user_mail.setGeometry(QtCore.QRect(10, 80, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.user_mail.setFont(font)
        self.user_mail.setObjectName("user_mail")

        self.user_phone = QtWidgets.QLabel(parent=self.frame_3)
        self.user_phone.setGeometry(QtCore.QRect(10, 120, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.user_phone.setFont(font)
        self.user_phone.setObjectName("user_phone")

        self.user_contract = QtWidgets.QLabel(parent=self.frame_3)
        self.user_contract.setGeometry(QtCore.QRect(10, 160, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.user_contract.setFont(font)
        self.user_contract.setObjectName("user_contract")

        self.user_login = QtWidgets.QLabel(parent=self.frame_3)
        self.user_login.setGeometry(QtCore.QRect(10, 200, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.user_login.setFont(font)
        self.user_login.setObjectName("user_login")

        self.user_ident = QtWidgets.QLabel(parent=self.frame_3)
        self.user_ident.setGeometry(QtCore.QRect(10, 40, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.user_ident.setFont(font)
        self.user_ident.setObjectName("user_id")

        self.tabWidget.addTab(self.Info, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 20, 281, 111))
        self.frame_4.setStyleSheet("border-radius: 15;\n"
"background-color:  rgb(229, 229, 229)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.user_credit = QtWidgets.QLabel(parent=self.frame_4)
        self.user_credit.setGeometry(QtCore.QRect(90, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.user_credit.setFont(font)
        self.user_credit.setObjectName("user_credit")
        self.frame_5 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_5.setGeometry(QtCore.QRect(10, 150, 281, 111))
        self.frame_5.setStyleSheet("border-radius: 15;\n"
"background-color:  rgb(229, 229, 229)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setObjectName("frame_5")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.price_per_month = QtWidgets.QLabel(parent=self.frame_5)
        self.price_per_month.setGeometry(QtCore.QRect(100, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.price_per_month.setFont(font)
        self.price_per_month.setObjectName("price_per_month")
        self.frame_6 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_6.setGeometry(QtCore.QRect(10, 280, 281, 171))
        self.frame_6.setStyleSheet("background-color:  rgb(229, 229, 229);\n"
"border-radius: 15;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setObjectName("frame_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.payment_data = QtWidgets.QLabel(parent=self.frame_6)
        self.payment_data.setGeometry(QtCore.QRect(20, 70, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.payment_data.setFont(font)
        self.payment_data.setObjectName("payment_data")

        self.frame_7 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_7.setGeometry(QtCore.QRect(330, 20, 341, 421))
        self.frame_7.setStyleSheet("border-radius: 15;\n"
"background-color:  rgb(229, 229, 229)")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_7.setObjectName("frame_7")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.scrollArea_3 = QtWidgets.QScrollArea(parent=self.frame_7)
        self.scrollArea_3.setGeometry(QtCore.QRect(9, 49, 321, 351))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")


        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.button_add_doc = QtWidgets.QPushButton(parent=self.tab_3)
        self.button_add_doc.setGeometry(QtCore.QRect(20, 30, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        font.setBold(True)
        self.button_add_doc.setFont(font)
        self.button_add_doc.setStyleSheet("border-radius: 15;\n"
"background-color:  rgb(229, 229, 229)")
        self.button_add_doc.setObjectName("button_add_doc")
        self.frame_8 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame_8.setGeometry(QtCore.QRect(20, 110, 661, 341))
        self.frame_8.setStyleSheet("border-radius: 15;\n"
"background-color:  rgb(229, 229, 229)")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_8.setObjectName("frame_8")

        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_8)
        self.scrollArea.setGeometry(QtCore.QRect(10, 30, 641, 301))
        self.scrollArea.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.scrollArea.setStyleSheet("background-color: transparent;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")


        self.scroll_widget_app = QtWidgets.QWidget()
        self.scroll_layout_app = QtWidgets.QVBoxLayout(self.scroll_widget_app)
        self.scroll_layout_app.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea.setWidget(self.scroll_widget_app)



        self.label_8 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_31 = QtWidgets.QWidget()
        self.tab_31.setObjectName("tab_31")
        self.frame_9 = QtWidgets.QFrame(parent=self.tab_31)
        self.frame_9.setGeometry(QtCore.QRect(10, 10, 671, 441))
        self.frame_9.setStyleSheet("border-radius: 15;\n"
"background-color:  rgb(229, 229, 229)")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_9.setObjectName("frame_9")
        self.scrollArea_4 = QtWidgets.QScrollArea(parent=self.frame_9)
        self.scrollArea_4.setGeometry(QtCore.QRect(10, 10, 651, 411))
        self.scrollArea_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.scrollArea_4.setStyleSheet("background-color: transparent;")
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 651, 411))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.tabWidget.addTab(self.tab_31, "")
        self.label_13 = QtWidgets.QLabel(parent=Dialog)
        self.label_13.setGeometry(QtCore.QRect(210, 30, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(24)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ФИО:"))
        # self.user_name.setText(_translate("Dialog", "ФАМИЛИЯ ИМЯ ОТЧЕСТВО"))
        self.label_5.setText(_translate("Dialog", "Информация о комнате"))
        self.user_room.setText(_translate("Dialog", "Номер комнаты"))
        self.label_15.setText(_translate("Dialog", "Соседи:"))
        self.label_16.setText(_translate("Dialog", "Данные"))
        self.user_mail.setText(_translate("Dialog", "Почта: "))
        self.user_phone.setText(_translate("Dialog", "Телефон:"))
        self.user_contract.setText(_translate("Dialog", "Договор:"))
        self.user_login.setText(_translate("Dialog", "Логин:"))
        self.user_ident.setText(_translate("Dialog", "ID: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Info), _translate("Dialog", "Профиль"))
        self.label_2.setText(_translate("Dialog", "Состояние счета:"))
        self.user_credit.setText(_translate("Dialog", "Total"))
        self.label_3.setText(_translate("Dialog", "Стоимость в месяц:"))
        self.price_per_month.setText(_translate("Dialog", "price"))
        self.label_7.setText(_translate("Dialog", "Реквизиты:"))
        self.payment_data.setText(_translate("Dialog", "№12231231231"))
        self.label_4.setText(_translate("Dialog", "История операций"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Оплата"))
        self.button_add_doc.setText(_translate("Dialog", "Написать заявление"))
        self.label_8.setText(_translate("Dialog", "Заявления"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", " Заявления"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_31), _translate("Dialog", "Новости"))
        self.label_13.setText(_translate("Dialog", "Добро пожаловать"))
