from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(704, 587)
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 701, 581))
        self.tabWidget.setObjectName("tabWidget")

        self.Info = QtWidgets.QWidget()
        self.Info.setObjectName("Info")

        self.label_2 = QtWidgets.QLabel(parent=self.Info)
        self.label_2.setGeometry(QtCore.QRect(50, 260, 49, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.Info)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(parent=self.Info)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(parent=self.Info)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 101, 31))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(parent=self.Info)
        self.label_7.setGeometry(QtCore.QRect(30, 130, 101, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.Info)
        self.label_8.setGeometry(QtCore.QRect(20, 330, 101, 31))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.Info, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_9 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(60, 190, 49, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(50, 70, 111, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(90, 280, 111, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(80, 360, 111, 16))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 161, 31))
        self.pushButton.setObjectName("pushButton")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.tab_3)
        self.scrollArea.setGeometry(QtCore.QRect(20, 100, 661, 80))
        self.scrollArea.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 659, 78))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_31 = QtWidgets.QWidget()
        self.tab_31.setObjectName("tab_31")
        self.tabWidget.addTab(self.tab_31, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "payment"))
        self.label_3.setText(_translate("Dialog", "Состояние счета"))
        self.label.setText(_translate("Dialog", "ФИО"))
        self.label_4.setText(_translate("Dialog", "Номер комнаты"))
        self.label_7.setText(_translate("Dialog", "Номер договора"))
        self.label_8.setText(_translate("Dialog", "номер телефона"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Info), _translate("Dialog", "Profile"))
        self.label_9.setText(_translate("Dialog", "payment"))
        self.label_10.setText(_translate("Dialog", "Состояние счета"))
        self.label_11.setText(_translate("Dialog", "Реквизиты"))
        self.label_12.setText(_translate("Dialog", "Номер догова"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Payment"))
        self.pushButton.setText(_translate("Dialog", "Написать заявление"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", " statements"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_31), _translate("Dialog", "Страница"))
if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MWindow()
    window.show()
    sys.exit(app.exec())